{
 "title": "Dragonite",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "inter", "label": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "area",
    "label": "Area",
    "query": {
     "query": "label_values(dragonite_location_handled_sum, area) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Location Handling Time / $area / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"pokemon\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"pokemon\"}[$inter])\n)",
     "legendFormat": "Pokemon"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"fort\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"fort\"}[$inter])\n)",
     "legendFormat": "Fort"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"scout\", exported_job=\"scout\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"scout\", exported_job=\"scout\"}[$inter])\n)",
     "legendFormat": "Scout"
    },
    {
     "expr": "avg(\n  rate(dragonite_location_handled_sum{area=~\"$area\", exported_job=\"quest\"}[$inter]) /\n  rate(dragonite_location_handled_counter{area=~\"$area\", exported_job=\"quest\"}[$inter])\n)",
     "legendFormat": "Quest"
    }
   ]
  },
  {
   "title": "GMO Retries / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"0\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "0"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"1\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "1"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"2\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "2"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"3\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "3"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"4\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "4"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"5\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "5"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"6\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "6"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"7\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "7"
    },
    {
     "expr": "sum(increase(dragonite_gmo_success_tries{tries=~\"8\"}[$inter:])) / sum(increase(dragonite_gmo_success_tries{tries=~\".*\"}[$inter:])) * 100",
     "legendFormat": "8"
    }
   ]
  },
  {
   "title": "RPC Response / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Success\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Account Suspended Rate Limited\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Account Suspended Rate Limited"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Action Error\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Action Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Cancelled Request\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Cancelled Request"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"No Retries Error\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "No Retries Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Parsing Error\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Parsing Error"
    },
    {
     "expr": "sum(increase(dragonite_rpc_response{status=~\"Undefined\"}[$inter:])) / sum(increase(dragonite_rpc_response{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Undefined"
    }
   ]
  },
  {
   "title": "GMO Hits / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Success\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Empty\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Empty"
    },
    {
     "expr": "sum(increase(dragonite_gmo_hits{status=~\"Failed\"}[$inter:])) / sum(increase(dragonite_gmo_hits{status=~\".*\"}[$inter:])) * 100",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Auth PTC / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_auth_ptc[$inter])* $inter",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Account Status / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(dragonite_account_status[$inter])*$inter",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Scout Queue / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "dragonite_scout_queue_size", "legendFormat": "Queue size" }
   ]
  },
  {
   "title": "Quest Handling Time / $inter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dragonite_location_handled_sum{exported_job=\"quest\"}[$inter]) / rate(dragonite_location_handled_counter{exported_job=\"quest\"}[$inter])",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Config in time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dragonite_config_allow_consecutive_failures",
     "legendFormat": "allow_consecutive_failures"
    },
    {
     "expr": "dragonite_config_fort_location_delay",
     "legendFormat": "fort_location_delay"
    },
    {
     "expr": "dragonite_config_location_delay",
     "legendFormat": "location_delay"
    },
    { "expr": "dragonite_config_max_retries", "legendFormat": "max_retries" },
    {
     "expr": "dragonite_config_no_pokemon_delay",
     "legendFormat": "no_pokemon_delay"
    },
    {
     "expr": "dragonite_config_rpc_12_disable_count",
     "legendFormat": "rpc_12_disable_count"
    }
   ]
  }
 ]
}